# Generated by Django 4.2.2 on 2023-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_description_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
