# Generated by Django 4.2.2 on 2023-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_open',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
